version: "3.3"
services:
  fast-gpt:
    image: fast-gpt:0.1
    environment:
      AXIOS_PROXY_HOST: 127.0.0.1
      AXIOS_PROXY_PORT: 7890
      MY_MAIL: 2569624033@qq.com
      MAILE_CODE: wfddhnaypyhveage
      TOKEN_KEY: b6049445-ec95-4903-a7b3-d193632840f4
      MONGODB_URI: mongodb://username:password@mongo:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
      OPENAIKEY: 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
      REDIS_URL: redis://default:psw1234@redis-stack:6379
    # network_mode: host
    restart: always
    container_name: fast-gpt
  mongodb:
    image: mongo:6.0.4
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - /Users/xuancao/WebstormProjects/FastGPT/docker/mongo/data:/data/db
      - /Users/xuancao/WebstormProjects/FastGPT/docker/mongo/logs:/data/logs
    ports:
      - 27017:27017
  nginx:
    image: nginx:alpine3.17
    container_name: nginx
    restart: always
    # network_mode: host
    ports:
      - "8080:80"
    volumes:
      - /Users/xuancao/WebstormProjects/FastGPT/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  redis-stack:
    image: redis/redis-stack:6.2.6-v6
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - "8100:6379"
      - "8101:8001"
    environment:
      - REDIS_ARGS=--requirepass psw1234
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Users/xuancao/WebstormProjects/FastGPT/docker/redis/redis.conf:/redis.conf
      - /Users/xuancao/WebstormProjects/FastGPT/docker/redis/data:/data